# Generated by Django 3.2.8 on 2021-10-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=154)),
                ('phone', models.CharField(max_length=11)),
                ('number', models.IntegerField()),
                ('gender', models.CharField(choices=[('1', 'Female'), ('2', 'Male'), ('3', 'Other'), ('4', 'Prefer Not Say')], max_length=50)),
                ('path', models.CharField(choices=[('1', 'Full Stack Developer'), ('2', 'Data Science'), ('3', 'AWS')], max_length=50)),
            ],
        ),
    ]
