# Generated by Django 3.2.8 on 2021-10-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0002_alter_register_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='path',
            field=models.CharField(choices=[('Full Stack Developer', 'Full Stack Developer'), ('Data Science', 'Data Science'), ('AWS', 'AWS')], max_length=50),
        ),
    ]
